# The ItemsMerging plugin configuration

enable_certain_item: false

Item: DIRT

combineItems:
  - sourceItemID: 21
    targetItemID: 3
  - sourceItemID: 26
    targetItemID: 8
  - sourceItemID: 9
    targetItemID: 9

